Error message and comment improvements
escamoteur/watch_it pull request #3
Opened 2023-06-29 13:48 UTC by kevlar700

Inform the user that watches must occur within a watching_widget within error messages.

2023-06-29 19:12 UTC, escamoteur commented
Thanks a lot, I will review the PR over the weekend

Thomas
Am 29. Juni 2023, 15:49 +0200 schrieb Kevin Chadwick ***@***.***>:
> Inform the user that watches must occur within a watching_widget within error messages.
> You can view, comment on, or merge this pull request online at:
> https://github.com/escamoteur/watch_it/pull/3
> Commit Summary
>
> • ce3f334 Error message and comment improvements
> • f02ea44 Merge pull request #1 from kevlar700/kevlar700-error-message
>
> File Changes
> (1 file)
>
> • M lib/src/watch_it.dart (60)
>
> Patch Links:
>
> • https://github.com/escamoteur/watch_it/pull/3.patch
> • https://github.com/escamoteur/watch_it/pull/3.diff
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-07-03 17:42 UTC, escamoteur requested changes
Some small things, but many, many thanks for the improvements.
I merge when you fix the requested changes.

2023-07-03 17:42 UTC, escamoteur commented on lib/src/watch_it.dart
> +      'watch can only be called inside a build function within a WatchingWidget');
or a widget using the WhatchItMixin

2023-07-03 17:42 UTC, escamoteur commented on lib/src/watch_it.dart
> +      'watch can only be called inside a build function within a WatchingWidget');
sames as above also name the WatchItMixin

2023-07-03 17:42 UTC, escamoteur commented on lib/src/watch_it.dart
> +      'watch can only be called inside a build function within a WatchingWidget');
same as above

2023-07-03 17:42 UTC, escamoteur commented on lib/src/watch_it.dart
> +      'watchIt can only be called inside a build function within a WatchingWidget');
same as above

2023-07-09 13:23 UTC, escamoteur commented
I know its only a nit but because how PRs work, it would be nice if you could add the small changes

2023-07-09 14:08 UTC, kevlar700 commented
I don't believe I got an email until just now. I shall try to sort this later today.

2023-08-24 06:11 UTC, merged